; 8051 CALCULATOR V3 - DISPLAY CONTROLLER, UART TWO-WIRE LINK
; Controller 2 owns the 16x2 LCD and all presentation formatting.
; It receives semantic events and result/error data from the process controller.
;
; DISPLAY CONTROLLER CONNECTIONS
;   RX / message input  : P3.0 <- process-controller P3.1 (TX)
;   TX / ACK output     : P3.1 -> process-controller P3.0 (RX)
;   LCD data D0-D7      : P1.0-P1.7
;   LCD RS              : P2.0
;   LCD RW              : P2.1
;   LCD EN              : P2.2
;   Both controllers must share ground.
;
; There is NO parallel event bus.  The built-in 8051 UART receives each message
; byte at 9600 baud (11.0592 MHz crystal), then returns 06H ACK.
;
; LCD POLICY
;   Line 1 = complete entered expression and operator symbols
;   Line 2 = mode prompt while idle, then right-aligned result or error text

EV_OP_ADD      EQU 0C0H
EV_OP_SUB      EQU 0C1H
EV_OP_MUL      EQU 0C2H
EV_OP_DIV      EQU 0C3H
EV_OP_AND      EQU 0C4H
EV_OP_OR       EQU 0C5H
EV_OP_XOR      EQU 0C6H
EV_OP_NOT      EQU 0C7H
EV_OP_SQUARE   EQU 0C8H
EV_RESULT_DEC  EQU 0D0H
EV_RESULT_BIN  EQU 0D1H
EV_ERROR       EQU 0D2H
EV_STARTUP     EQU 0E0H
EV_MODE_AR     EQU 0E1H
EV_MODE_LOG    EQU 0E2H
EV_MODE_ADD    EQU 0E3H
EV_CLEAR       EQU 0E4H
EV_MENU        EQU 0E5H
EV_ANS         EQU 0E6H
EV_EQUALS      EQU 0E7H

RX_BYTE       EQU 30H
DISPLAY_MODE  EQU 31H           ; 0 menu, 1 arithmetic, 2 logical, 3 additional
RESULT_H      EQU 32H
RESULT_L      EQU 33H
TMP_H         EQU 34H
TMP_L         EQU 35H
QUO_H         EQU 36H
QUO_L         EQU 37H
REM_L         EQU 38H
DIGIT_COUNT   EQU 39H
BIT_TEMP      EQU 3AH
LCD_LINE1     EQU 080H
LCD_LINE2     EQU 0C0H
LCD_WIDTH     EQU 10H
; 20H.0 = received decimal result is negative

    ORG 0000H
    LJMP MAIN

MAIN:
    MOV SP, #5FH
    MOV P1, #00H                ; Known LCD data-bus state
    SETB P3.0                   ; Release UART RX pin for input
    SETB P3.1                   ; UART TX idles high
    MOV P2, #00H                ; LCD RS=0, RW=0, EN=0
    MOV DISPLAY_MODE, #00H
    CLR 20H.0
    LCALL UART_INIT
    LCALL LCD_POWER_DELAY
    LCALL LCD_INIT
    LCALL SHOW_STARTUP           ; LCD test is independent of the serial link

DISPLAY_LOOP:
    LCALL RECEIVE_BYTE
    MOV RX_BYTE, A

    ; Only 00H-09H are digit events.
    CJNE A, #0AH, $ + 3
    JNC CHECK_EVENT_STARTUP
    ADD A, #30H
    LCALL LCD_DATA
    LJMP DISPLAY_LOOP

CHECK_EVENT_STARTUP:
    MOV A, RX_BYTE
    CJNE A, #EV_STARTUP, CHECK_EVENT_MODE_AR
    LCALL SHOW_STARTUP
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_AR:
    CJNE A, #EV_MODE_AR, CHECK_EVENT_MODE_LOG
    MOV DISPLAY_MODE, #01H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_LOG:
    CJNE A, #EV_MODE_LOG, CHECK_EVENT_MODE_ADD
    MOV DISPLAY_MODE, #02H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_ADD:
    CJNE A, #EV_MODE_ADD, CHECK_EVENT_CLEAR
    MOV DISPLAY_MODE, #03H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_CLEAR:
    CJNE A, #EV_CLEAR, CHECK_EVENT_MENU
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MENU:
    CJNE A, #EV_MENU, CHECK_EVENT_ANS
    LCALL SHOW_MODE_MENU
    LJMP DISPLAY_LOOP
CHECK_EVENT_ANS:
    CJNE A, #EV_ANS, CHECK_EVENT_EQUALS
    LCALL SHOW_ANS_EXPRESSION
    LJMP DISPLAY_LOOP
CHECK_EVENT_EQUALS:
    CJNE A, #EV_EQUALS, CHECK_EVENT_RESULT_DEC
    MOV A, #'='
    LCALL LCD_DATA
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP

CHECK_EVENT_RESULT_DEC:
    CJNE A, #EV_RESULT_DEC, CHECK_EVENT_RESULT_BIN
    LCALL RECEIVE_DECIMAL_RESULT
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_BIN:
    CJNE A, #EV_RESULT_BIN, CHECK_EVENT_ERROR
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LCALL LCD_PRINT_BIN8_RIGHT
    LJMP DISPLAY_LOOP
CHECK_EVENT_ERROR:
    CJNE A, #EV_ERROR, CHECK_EVENT_OPERATOR
    LCALL RECEIVE_BYTE
    LCALL DISPLAY_ERROR
    LJMP DISPLAY_LOOP

CHECK_EVENT_OPERATOR:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_ADD, TRY_OP_SUB
    SJMP DISPLAY_OPERATOR
TRY_OP_SUB:
    CJNE A, #EV_OP_SUB, TRY_OP_MUL
    SJMP DISPLAY_OPERATOR
TRY_OP_MUL:
    CJNE A, #EV_OP_MUL, TRY_OP_DIV
    SJMP DISPLAY_OPERATOR
TRY_OP_DIV:
    CJNE A, #EV_OP_DIV, TRY_OP_AND
    SJMP DISPLAY_OPERATOR
TRY_OP_AND:
    CJNE A, #EV_OP_AND, TRY_OP_OR
    SJMP DISPLAY_OPERATOR
TRY_OP_OR:
    CJNE A, #EV_OP_OR, TRY_OP_XOR
    SJMP DISPLAY_OPERATOR
TRY_OP_XOR:
    CJNE A, #EV_OP_XOR, TRY_OP_NOT
    SJMP DISPLAY_OPERATOR
TRY_OP_NOT:
    CJNE A, #EV_OP_NOT, TRY_OP_SQUARE
    SJMP DISPLAY_OPERATOR
TRY_OP_SQUARE:
    CJNE A, #EV_OP_SQUARE, DISPLAY_LOOP_JUMP

DISPLAY_OPERATOR:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_SQUARE, DISPLAY_ONE_OPERATOR
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'2'
    LCALL LCD_DATA
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_ONE_OPERATOR:
    CLR C
    SUBB A, #EV_OP_ADD
    MOV DPTR, #OPERATOR_SYMBOLS
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    MOV A, RX_BYTE
    CJNE A, #EV_OP_NOT, DISPLAY_BINARY_CURSOR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_BINARY_CURSOR:
    LCALL LCD_CURSOR_ON
DISPLAY_LOOP_JUMP:
    LJMP DISPLAY_LOOP

; HARDWARE UART RECEIVER AND ACK TRANSMITTER
UART_INIT:
    ANL TMOD, #0FH              ; Preserve Timer 0; configure Timer 1 only
    ORL TMOD, #020H             ; Timer 1 mode 2, 8-bit auto-reload
    ANL PCON, #07FH             ; SMOD=0
    MOV TH1, #0FDH              ; 9600 baud with 11.0592 MHz crystal
    MOV TL1, #0FDH
    MOV SCON, #050H             ; UART mode 1, receiver enabled
    CLR TI
    CLR RI
    SETB TR1
    RET

RECEIVE_BYTE:
    ; Receive on RX/P3.0 and acknowledge the byte on TX/P3.1.
RECEIVE_WAIT_BYTE:
    JNB RI, RECEIVE_WAIT_BYTE
    MOV A, SBUF
    CLR RI
    MOV RX_BYTE, A
    CLR TI
    MOV SBUF, #006H             ; ACK
RECEIVE_WAIT_ACK_SENT:
    JNB TI, RECEIVE_WAIT_ACK_SENT
    CLR TI
    MOV A, RX_BYTE
    RET

; SCREEN STATES
SHOW_STARTUP:
    MOV DISPLAY_MODE, #00H
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, #0C5H
    LCALL LCD_CMD
    MOV DPTR, #STR_READY
    LCALL LCD_PUTS
    LCALL READY_DELAY
    LJMP SHOW_MODE_MENU

SHOW_MODE_MENU:
    MOV DISPLAY_MODE, #00H
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV DPTR, #STR_SELECT_MODES
    LCALL LCD_PUTS
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV DPTR, #STR_MODE_MENU
    LCALL LCD_PUTS
    RET

SHOW_MODE_STATUS:
    MOV A, DISPLAY_MODE
    JZ SHOW_MODE_MENU
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, DISPLAY_MODE
    CJNE A, #01H, STATUS_LOGICAL
    MOV DPTR, #STR_ARITHMETIC
    SJMP PRINT_MODE_STATUS
STATUS_LOGICAL:
    CJNE A, #02H, STATUS_ADDITIONAL
    MOV DPTR, #STR_LOGICAL
    SJMP PRINT_MODE_STATUS
STATUS_ADDITIONAL:
    MOV DPTR, #STR_ADDITIONAL
PRINT_MODE_STATUS:
    LCALL LCD_PUTS
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

SHOW_ANS_EXPRESSION:
    MOV A, #01H
    LCALL LCD_CMD
    MOV DPTR, #STR_ANS
    LCALL LCD_PUTS
    LJMP LCD_CURSOR_ON

; RECEIVE AND FORMAT RESULTS
RECEIVE_DECIMAL_RESULT:
    LCALL RECEIVE_BYTE            ; Sign: 0 positive, 1 negative
    CLR 20H.0
    JZ RECEIVE_RESULT_MAGNITUDE
    SETB 20H.0
RECEIVE_RESULT_MAGNITUDE:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LJMP LCD_PRINT_U16_RIGHT

DISPLAY_ERROR:
    ; Error code arrives in A. Text belongs entirely to line 2.
    MOV RX_BYTE, A
    LCALL LCD_CURSOR_OFF
    LCALL LCD_CLEAR_LINE2
    MOV A, RX_BYTE
    CJNE A, #01H, ERR_CHK_ZERO
    MOV DPTR, #STR_ERR_OVERFLOW
    SJMP ERROR_PRINT
ERR_CHK_ZERO:
    CJNE A, #03H, ERR_CHK_INPUT
    MOV DPTR, #STR_ERR_DIV_ZERO
    SJMP ERROR_PRINT
ERR_CHK_INPUT:
    CJNE A, #04H, ERR_CHK_BINARY
    MOV DPTR, #STR_ERR_INPUT
    SJMP ERROR_PRINT
ERR_CHK_BINARY:
    CJNE A, #07H, ERR_CHK_BIT_COUNT
    MOV DPTR, #STR_ERR_BINARY
    SJMP ERROR_PRINT
ERR_CHK_BIT_COUNT:
    CJNE A, #08H, ERR_UNKNOWN
    MOV DPTR, #STR_ERR_8_BITS
    SJMP ERROR_PRINT
ERR_UNKNOWN:
    MOV DPTR, #STR_ERROR
ERROR_PRINT:
    LJMP LCD_PUTS

LCD_PRINT_BIN8_RIGHT:
    LCALL LCD_CURSOR_OFF
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #08H
BIN8_PADDING:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, BIN8_PADDING
    MOV BIT_TEMP, RESULT_L
    MOV R0, #08H
BIN8_PRINT_LOOP:
    MOV A, BIT_TEMP
    ANL A, #080H
    JZ BIN8_PRINT_ZERO
    MOV A, #'1'
    SJMP BIN8_WRITE
BIN8_PRINT_ZERO:
    MOV A, #'0'
BIN8_WRITE:
    LCALL LCD_DATA
    MOV A, BIT_TEMP
    RL A
    MOV BIT_TEMP, A
    DJNZ R0, BIN8_PRINT_LOOP
    RET

LCD_PRINT_U16_RIGHT:
    LCALL LCD_CURSOR_OFF
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_CONVERT
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #0FH
U16_ZERO_PAD:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, U16_ZERO_PAD
    MOV A, #'0'
    LCALL LCD_DATA
    RET
U16_CONVERT:
    MOV R0, #00H
U16_DIVIDE_LOOP:
    LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_DIVIDE_LOOP
    MOV DIGIT_COUNT, R0
    MOV A, R0
    JNB 20H.0, U16_ALIGN_COUNT_READY
    INC A
U16_ALIGN_COUNT_READY:
    MOV B, A
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, B
    MOV R1, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R1
    JZ U16_PADDING_DONE
U16_PADDING_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, U16_PADDING_LOOP
U16_PADDING_DONE:
    JNB 20H.0, U16_PRINT_PREPARE
    MOV A, #'-'
    LCALL LCD_DATA
U16_PRINT_PREPARE:
    MOV R0, DIGIT_COUNT
U16_PRINT_LOOP:
    POP ACC
    LCALL LCD_DATA
    DJNZ R0, U16_PRINT_LOOP
    RET

DIV_TMP_BY_10:
    MOV QUO_H, #00H
    MOV QUO_L, #00H
    MOV REM_L, #00H
    MOV R1, #16
DIV10_LOOP:
    CLR C
    MOV A, TMP_L
    RLC A
    MOV TMP_L, A
    MOV A, TMP_H
    RLC A
    MOV TMP_H, A
    MOV A, REM_L
    RLC A
    MOV REM_L, A
    CLR C
    MOV A, QUO_L
    RLC A
    MOV QUO_L, A
    MOV A, QUO_H
    RLC A
    MOV QUO_H, A
    MOV A, REM_L
    CLR C
    SUBB A, #10
    JC DIV10_LESS
    MOV REM_L, A
    ORL QUO_L, #01H
DIV10_LESS:
    DJNZ R1, DIV10_LOOP
    MOV TMP_H, QUO_H
    MOV TMP_L, QUO_L
    MOV A, REM_L
    RET

; LCD DRIVER: 8-BIT, TWO-LINE HD44780-COMPATIBLE DISPLAY
LCD_INIT:
    MOV A, #030H
    LCALL LCD_CMD
    LCALL LCD_DELAY
    MOV A, #030H
    LCALL LCD_CMD
    MOV A, #030H
    LCALL LCD_CMD
    MOV A, #038H
    LCALL LCD_CMD
    MOV A, #00CH
    LCALL LCD_CMD
    MOV A, #006H
    LCALL LCD_CMD
    MOV A, #001H
    LCALL LCD_CMD
    RET

LCD_CMD:
    CLR P2.0
    SJMP LCD_WRITE
LCD_DATA:
    SETB P2.0
LCD_WRITE:
    MOV P1, A
    CLR P2.1
    SETB P2.2
    LCALL SHORT_DELAY
    CLR P2.2
    LCALL LCD_DELAY
    RET

LCD_PUTS:
    CLR A
    MOVC A, @A+DPTR
    JZ LCD_PUTS_DONE
    LCALL LCD_DATA
    INC DPTR
    SJMP LCD_PUTS
LCD_PUTS_DONE:
    RET

LCD_CLEAR_LINE2:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
LCD_CLEAR_L2_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_CLEAR_L2_LOOP
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    RET

LCD_CURSOR_ON:
    MOV A, #00FH
    LJMP LCD_CMD
LCD_CURSOR_OFF:
    MOV A, #00CH
    LJMP LCD_CMD

LCD_POWER_DELAY:
    PUSH 00H
    PUSH 01H
    MOV R0, #80
LCD_POWER_D_OUTER:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_POWER_D_OUTER
    POP 01H
    POP 00H
    RET

SHORT_DELAY:
    NOP
    NOP
    RET

LCD_DELAY:
    PUSH 00H
    PUSH 01H
    MOV R0, #4
LCD_D_LOOP1:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_D_LOOP1
    POP 01H
    POP 00H
    RET

READY_DELAY:
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #8
READY_D_OUTER:
    MOV R0, #255
READY_D_MIDDLE:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, READY_D_MIDDLE
    DJNZ R2, READY_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

OPERATOR_SYMBOLS:  DB '+', '-', '*', '/', '&', '|', 'X', '~'
STR_READY:          DB 'READY', 00H
STR_ANS:            DB 'ANS', 00H
STR_SELECT_MODES:   DB 'MODES SELECTION', 00H
STR_MODE_MENU:      DB '1:AR 2:LOG 3:ADD', 00H
STR_ARITHMETIC:     DB 'ARITHMETIC', 00H
STR_LOGICAL:        DB 'LOGIC: 0/1 ONLY', 00H
STR_ADDITIONAL:     DB 'ADDITIONAL', 00H
STR_ERR_OVERFLOW:   DB 'ERROR:OVERFLOW', 00H
STR_ERR_DIV_ZERO:   DB 'ERROR:DIV ZERO', 00H
STR_ERR_INPUT:      DB 'ERROR:INPUT SIZE', 00H
STR_ERR_BINARY:     DB 'ERROR:USE 0/1', 00H
STR_ERR_8_BITS:     DB 'ERROR:MAX 8 BIT', 00H
STR_ERROR:          DB 'ERROR', 00H

    END
