; ==============================================================================
; MCU 1: COMPUTATION & MASTER CONTROLLER
; Keypad: P1.0-P1.7 | Comm: UART (P3.0, P3.1) @ 9600 baud (11.0592 MHz crystal)
; ==============================================================================

; ----- Scratch RAM ------------------------------------------------------------
DIGIT_TMP   EQU 30H
TMP_H       EQU 31H
TMP_L       EQU 32H
QUO_H       EQU 33H
QUO_L       EQU 34H
REM_H       EQU 35H
REM_L       EQU 36H
MC0         EQU 37H
MC1         EQU 38H
MC2         EQU 39H
MC3         EQU 3AH
PROD0       EQU 3BH
PROD1       EQU 3CH
PROD2       EQU 3DH
PROD3       EQU 3EH
MUL0        EQU 3FH
MUL1        EQU 40H
ERROR_CODE  EQU 41H
DIV_OVER    EQU 42H
DIGIT_COUNT EQU 43H
MODE        EQU 44H
OP1_BITS    EQU 45H
OP2_BITS    EQU 46H

LCD_LINE1   EQU 080H
LCD_LINE2   EQU 0C0H
LCD_WIDTH   EQU 10H

    ORG 0000H
    LJMP MAIN

; INITIALISATION
MAIN:
    MOV SP, #5FH                 ; Stack uses 60H upward
    MOV P1, #0FFH                ; Keypad port high
    
    ; Init UART: Mode 1, 8-bit, 9600 baud @ 11.0592 MHz
    MOV TMOD, #20H               ; Timer 1, Mode 2 (8-bit auto-reload)
    MOV TH1, #0FDH               ; 9600 baud
    MOV SCON, #50H               ; Mode 1, Receive Enable
    SETB TR1                     ; Start Timer 1
    
WAIT_FOR_SLAVE_BOOT:
    ; Wait for MCU 2 to finish LCD power-up delay and send 0xBB ready code
    JNB RI, $
    MOV A, SBUF
    CLR RI
    CJNE A, #0BBH, WAIT_FOR_SLAVE_BOOT

    LCALL SHOW_STARTUP

CALC_LOOP:
    LCALL KEYPAD_SCAN
    CJNE A, #0FFH, PROCESS_KEY
    LJMP CALC_LOOP

PROCESS_KEY:
    PUSH ACC
    LCALL WAIT_KEY_RELEASE
    POP ACC
    MOV DIGIT_TMP, A

    MOV A, MODE
    JNZ ACTIVE_MODE_KEY
    MOV A, DIGIT_TMP
    LCALL SELECT_MODE
    LJMP CALC_LOOP

ACTIVE_MODE_KEY:
    JNB 20H.1, CHECK_CLEAR_KEY
    CLR 20H.1
    MOV A, DIGIT_TMP
    CJNE A, #0FH, CHECK_CLEAR_KEY
    LCALL SHOW_MODE_MENU
    LJMP CALC_LOOP

CHECK_CLEAR_KEY:
    MOV A, DIGIT_TMP
    CJNE A, #0EH, CHECK_DIGIT
    LCALL CLEAR_CURRENT
    SETB 20H.1                   
    LJMP CALC_LOOP

CHECK_DIGIT:
    CJNE A, #0AH, $ + 3
    JNC CHECK_OPERATOR

    CJNE R7, #02H, DIGIT_NOT_LOCKED
    LJMP CALC_LOOP               
DIGIT_NOT_LOCKED:
    JNB 20H.3, DIGIT_ENTRY_READY
    LCALL START_NEW_ENTRY
DIGIT_ENTRY_READY:
    MOV A, MODE
    CJNE A, #02H, STORE_DECIMAL_DIGIT
    MOV A, DIGIT_TMP
    CJNE A, #02H, $ + 3
    JNC INVALID_BINARY_DIGIT
    LCALL ACCUMULATE_BINARY
    SJMP CHECK_DIGIT_RESULT

STORE_DECIMAL_DIGIT:
    MOV A, DIGIT_TMP
    LCALL ACCUMULATE_DIGIT
CHECK_DIGIT_RESULT:
    JB 20H.0, DIGIT_ERROR
    MOV A, DIGIT_TMP
    ADD A, #30H
    LCALL LCD_DATA
    LJMP CALC_LOOP

INVALID_BINARY_DIGIT:
    MOV ERROR_CODE, #07H
    LCALL SET_ERROR
DIGIT_ERROR:            
    LCALL DISPLAY_ERROR
    LJMP CALC_LOOP

CHECK_OPERATOR:
    MOV A, DIGIT_TMP
    CJNE A, #0FH, CHECK_MODE_OPERATOR
    JNB 20H.3, HASH_EXECUTE
    LJMP CALC_LOOP

CHECK_MODE_OPERATOR:
    CJNE A, #0EH, $ + 3
    JNC UNKNOWN_KEY
    MOV A, MODE
    CJNE A, #03H, PREPARE_MODE_OPERATOR
    MOV A, DIGIT_TMP
    CJNE A, #0AH, UNKNOWN_KEY    

PREPARE_MODE_OPERATOR:
    LCALL PREPARE_OPERATOR_ENTRY
    JNB 20H.0, DECODE_MODE_OPERATOR
    LJMP CALC_LOOP

DECODE_MODE_OPERATOR:
    MOV A, MODE
    CJNE A, #01H, CHECK_LOGIC_MODE
    MOV A, DIGIT_TMP
    CLR C
    SUBB A, #09H
    MOV R6, A
    MOV A, DIGIT_TMP
    CLR C
    SUBB A, #0AH
    MOV DPTR, #NORMAL_SYMBOLS
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    LJMP NEXT_OPERAND

CHECK_LOGIC_MODE:
    CJNE A, #02H, DO_SQUARE
    MOV A, DIGIT_TMP
    CJNE A, #0DH, LOGIC_BINARY_OPERATOR
    MOV R6, #08H
    MOV A, #'~'
    LCALL LCD_DATA
    LJMP UNARY_PENDING

DO_SQUARE: 
    MOV R6, #09H
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'2'
    LCALL LCD_DATA
    LJMP UNARY_PENDING

LOGIC_BINARY_OPERATOR:  
    CLR C
    SUBB A, #05H                 
    MOV R6, A
    MOV A, DIGIT_TMP
    CLR C
    SUBB A, #0AH
    MOV DPTR, #LOGIC_SYMBOLS
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    LJMP NEXT_OPERAND

HASH_EXECUTE: 
    LCALL LCD_CURSOR_OFF         
    MOV A, #'='
    LCALL LCD_DATA
    JB 20H.0, EQUALS_SHOW
    MOV ERROR_CODE, #00H
    LCALL EXECUTE_MATH
EQUALS_SHOW:            
    LCALL DISPLAY_RESULT
    LJMP CALC_LOOP
UNKNOWN_KEY:            LJMP CALC_LOOP
NEXT_OPERAND:           MOV R7, #01H
    LCALL LCD_CURSOR_ON          
    LJMP CALC_LOOP
UNARY_PENDING:          MOV R7, #02H
    LCALL LCD_CURSOR_OFF         
    LJMP CALC_LOOP

; ------------------------------------------------------------------------------
; UART VIRTUAL LCD DRIVER
; ------------------------------------------------------------------------------
; Instead of physical pins, send a 2-byte packet to MCU 2: [TYPE] [BYTE]
; TYPE: 0x00 = Command, 0x01 = Data. Then wait for 0xAA Ack.

LCD_CMD:
    PUSH ACC
    MOV A, #00H                  ; 0 = CMD Type
    LCALL UART_TX
    POP ACC                      ; Retrieve actual command byte
    LCALL UART_TX
    LCALL UART_WAIT_ACK
    RET

LCD_DATA:
    PUSH ACC
    MOV A, #01H                  ; 1 = DATA Type
    LCALL UART_TX
    POP ACC                      ; Retrieve actual data byte
    LCALL UART_TX
    LCALL UART_WAIT_ACK
    RET

UART_TX:
    MOV SBUF, A
    JNB TI, $
    CLR TI
    RET

UART_WAIT_ACK:
    JNB RI, $
    MOV A, SBUF                  ; Consume the 0xAA Ack
    CLR RI
    RET

LCD_PUTS:
    CLR A
    MOVC A, @A+DPTR
    JZ LCD_PUTS_DONE
    LCALL LCD_DATA
    INC DPTR
    SJMP LCD_PUTS
LCD_PUTS_DONE:          RET

LCD_CLEAR_LINE2:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
LCD_CLEAR_L2_LOOP:      
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_CLEAR_L2_LOOP
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    RET

LCD_CURSOR_ON:
    MOV A, #00FH
    LJMP LCD_CMD

LCD_CURSOR_OFF:
    MOV A, #00CH
    LJMP LCD_CMD

READY_DELAY: 
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #8
READY_D_OUTER:          MOV R0, #255
READY_D_MIDDLE:         MOV R1, #255
    DJNZ R1, $
    DJNZ R0, READY_D_MIDDLE
    DJNZ R2, READY_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

; ------------------------------------------------------------------------------
; EVERYTHING BELOW HERE (STATE & MATH) REMAINS 100% IDENTICAL TO ORIGINAL
; ------------------------------------------------------------------------------
RESET_STATE:
    MOV R2, #00H
    MOV R3, #00H
    MOV R4, #00H
    MOV R5, #00H
    MOV R6, #00H
    MOV R7, #00H
    MOV ERROR_CODE, #00H
    MOV OP1_BITS, #00H
    MOV OP2_BITS, #00H
    CLR 20H.0
    CLR 20H.1
    CLR 20H.2
    CLR 20H.3
    RET

SHOW_STARTUP:
    MOV MODE, #00H
    LCALL RESET_STATE
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, #0C5H
    LCALL LCD_CMD
    MOV DPTR, #STR_READY
    LCALL LCD_PUTS
    LCALL READY_DELAY
    LJMP SHOW_MODE_MENU

SHOW_MODE_MENU:
    MOV MODE, #00H
    LCALL RESET_STATE
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV DPTR, #STR_SELECT_MODES
    LCALL LCD_PUTS
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV DPTR, #STR_MODE_MENU
    LCALL LCD_PUTS
    RET

SELECT_MODE:
    CJNE A, #01H, SELECT_MODE_2
    MOV MODE, #01H
    SJMP MODE_SELECTED
SELECT_MODE_2:          CJNE A, #02H, SELECT_MODE_3
    MOV MODE, #02H
    SJMP MODE_SELECTED
SELECT_MODE_3:          CJNE A, #03H, SELECT_MODE_DONE
    MOV MODE, #03H
MODE_SELECTED:          LCALL RESET_STATE
    LJMP SHOW_MODE_STATUS
SELECT_MODE_DONE:       RET

SHOW_MODE_STATUS:
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, MODE
    CJNE A, #01H, STATUS_LOGICAL
    MOV DPTR, #STR_ARITHMETIC
    SJMP PRINT_MODE_STATUS
STATUS_LOGICAL:         CJNE A, #02H, STATUS_ADDITIONAL
    MOV DPTR, #STR_LOGICAL
    SJMP PRINT_MODE_STATUS
STATUS_ADDITIONAL:      MOV DPTR, #STR_ADDITIONAL
PRINT_MODE_STATUS:      LCALL LCD_PUTS
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

CLEAR_CURRENT:
    LCALL RESET_STATE
    LJMP SHOW_MODE_STATUS

START_NEW_ENTRY:
    LJMP CLEAR_CURRENT

PREPARE_ANS_EXPRESSION:
    JNB 20H.3, PREPARE_ANS_DONE
    MOV R4, #00H
    MOV R5, #00H
    MOV R6, #00H
    MOV R7, #00H
    MOV ERROR_CODE, #00H
    MOV OP2_BITS, #00H
    CLR 20H.0
    CLR 20H.3
    MOV A, #01H
    LCALL LCD_CMD
    MOV DPTR, #STR_ANS
    LCALL LCD_PUTS
PREPARE_ANS_DONE:       RET

PREPARE_OPERATOR_ENTRY:
    JB 20H.0, PREPARE_OPERATOR_DONE
    JB 20H.3, PREPARE_OPERATOR_USE_ANS
    CJNE R7, #01H, PREPARE_OPERATOR_DONE
    LCALL EXECUTE_MATH
    JB 20H.0, PREPARE_OPERATOR_ERROR
    SETB 20H.3
PREPARE_OPERATOR_USE_ANS:LCALL PREPARE_ANS_EXPRESSION
    RET
PREPARE_OPERATOR_ERROR: LCALL DISPLAY_ERROR
PREPARE_OPERATOR_DONE:  RET

KEYPAD_SCAN:
    MOV P1, #0F0H
    MOV A, P1
    ANL A, #0F0H
    CJNE A, #0F0H, KEY_FOUND
    MOV A, #0FFH
    RET
KEY_FOUND:              LCALL DEBOUNCE_DELAY
    MOV P1, #0F0H
    MOV A, P1
    ANL A, #0F0H
    CJNE A, #0F0H, SCAN_ROW_0
    MOV A, #0FFH
    RET
SCAN_ROW_0:             MOV P1, #0FEH
    MOV A, P1
    JNB ACC.4, GOT_KEY_1
    JNB ACC.5, GOT_KEY_2
    JNB ACC.6, GOT_KEY_3
    JNB ACC.7, GOT_KEY_A
SCAN_ROW_1:             MOV P1, #0FDH
    MOV A, P1
    JNB ACC.4, GOT_KEY_4
    JNB ACC.5, GOT_KEY_5
    JNB ACC.6, GOT_KEY_6
    JNB ACC.7, GOT_KEY_B
SCAN_ROW_2:             MOV P1, #0FBH
    MOV A, P1
    JNB ACC.4, GOT_KEY_7
    JNB ACC.5, GOT_KEY_8
    JNB ACC.6, GOT_KEY_9
    JNB ACC.7, GOT_KEY_C
SCAN_ROW_3:             MOV P1, #0F7H
    MOV A, P1
    JNB ACC.4, GOT_KEY_STAR
    JNB ACC.5, GOT_KEY_0
    JNB ACC.6, GOT_KEY_HASH
    JNB ACC.7, GOT_KEY_D
    MOV A, #0FFH
    RET
GOT_KEY_0:     MOV A, #00H
               RET
GOT_KEY_1:     MOV A, #01H
               RET
GOT_KEY_2:     MOV A, #02H
               RET
GOT_KEY_3:     MOV A, #03H
               RET
GOT_KEY_4:     MOV A, #04H
               RET
GOT_KEY_5:     MOV A, #05H
               RET
GOT_KEY_6:     MOV A, #06H
               RET
GOT_KEY_7:     MOV A, #07H
               RET
GOT_KEY_8:     MOV A, #08H
               RET
GOT_KEY_9:     MOV A, #09H
               RET
GOT_KEY_A:     MOV A, #0AH
               RET
GOT_KEY_B:     MOV A, #0BH
               RET
GOT_KEY_C:     MOV A, #0CH
               RET
GOT_KEY_D:     MOV A, #0DH
               RET
GOT_KEY_STAR:  MOV A, #0EH
               RET
GOT_KEY_HASH:  MOV A, #0FH
               RET

WAIT_KEY_RELEASE:
    MOV P1, #0F0H
    MOV A, P1
    ANL A, #0F0H
    CJNE A, #0F0H, WAIT_KEY_RELEASE
    LCALL DEBOUNCE_DELAY
    RET

DEBOUNCE_DELAY:
    MOV R0, #20
DEBOUNCE_OUTER:         MOV R1, #255
    DJNZ R1, $
    DJNZ R0, DEBOUNCE_OUTER
    RET

ACCUMULATE_BINARY:
    MOV DIGIT_TMP, A
    CJNE R7, #00H, BINARY_OP2
    MOV A, OP1_BITS
    CJNE A, #08H, $ + 3
    JNC BINARY_TOO_LONG
    MOV A, R3
    RL A
    ORL A, DIGIT_TMP
    MOV R3, A
    MOV R2, #00H
    INC OP1_BITS
    RET
BINARY_OP2:             MOV A, OP2_BITS
    CJNE A, #08H, $ + 3
    JNC BINARY_TOO_LONG
    MOV A, R5
    RL A
    ORL A, DIGIT_TMP
    MOV R5, A
    MOV R4, #00H
    INC OP2_BITS
    RET
BINARY_TOO_LONG:        MOV ERROR_CODE, #08H
    LJMP SET_ERROR

ACCUMULATE_DIGIT:
    MOV DIGIT_TMP, A
    CJNE R7, #00H, ACC_OP2
    MOV TMP_H, R2
    MOV TMP_L, R3
    LCALL MUL10_TMP_CHECK
    JC INPUT_TOO_LARGE
    MOV A, TMP_L
    ADD A, DIGIT_TMP
    MOV TMP_L, A
    MOV A, TMP_H
    ADDC A, #00H
    JC INPUT_TOO_LARGE
    MOV TMP_H, A
    MOV R2, TMP_H
    MOV R3, TMP_L
    RET
ACC_OP2:                MOV TMP_H, R4
    MOV TMP_L, R5
    LCALL MUL10_TMP_CHECK
    JC INPUT_TOO_LARGE
    MOV A, TMP_L
    ADD A, DIGIT_TMP
    MOV TMP_L, A
    MOV A, TMP_H
    ADDC A, #00H
    JC INPUT_TOO_LARGE
    MOV TMP_H, A
    MOV R4, TMP_H
    MOV R5, TMP_L
    RET

MUL10_TMP_CHECK:
    MOV A, TMP_L
    MOV B, #10
    MUL AB
    MOV TMP_L, A
    MOV REM_L, B
    MOV A, TMP_H
    MOV B, #10
    MUL AB
    MOV TMP_H, A
    MOV A, B
    JNZ MUL10_OVERFLOW
    MOV A, TMP_H
    ADD A, REM_L
    MOV TMP_H, A
    JC MUL10_OVERFLOW
    CLR C
    RET
MUL10_OVERFLOW:         SETB C
    RET
INPUT_TOO_LARGE:        MOV ERROR_CODE, #04H
    LJMP SET_ERROR

EXECUTE_MATH:
    MOV A, R6
    JZ NO_OPERATOR_SELECTED
    CJNE A, #0AH, $ + 3
    JNC NO_OPERATOR_SELECTED
    DEC A
    MOV B, #03H
    MUL AB
    MOV DPTR, #ALU_JUMP_TABLE
    JMP @A+DPTR
NO_OPERATOR_SELECTED:   RET

ALU_JUMP_TABLE:
    LJMP MATH_ADD
    LJMP MATH_SUB
    LJMP MATH_MUL
    LJMP MATH_DIV
    LJMP LOGIC_AND
    LJMP LOGIC_OR
    LJMP LOGIC_XOR
    LJMP LOGIC_NOT
    LJMP MATH_SQUARE

MATH_ADD:
    JB 20H.2, ADD_TO_NEGATIVE_ANS
    MOV A, R3
    ADD A, R5
    MOV R3, A
    MOV A, R2
    ADDC A, R4
    MOV R2, A
    JNC ADD_OK
    LJMP ARITH_OVERFLOW
ADD_OK:                 RET
ADD_TO_NEGATIVE_ANS:
    MOV A, R4
    CLR C
    SUBB A, R2
    JC ADD_NEG_MAG_LARGER
    JNZ ADD_POS_MAG_LARGER
    MOV A, R5
    CLR C
    SUBB A, R3
    JC ADD_NEG_MAG_LARGER
ADD_POS_MAG_LARGER:
    CLR C
    MOV A, R5
    SUBB A, R3
    MOV R3, A
    MOV A, R4
    SUBB A, R2
    MOV R2, A
    CLR 20H.2
    RET
ADD_NEG_MAG_LARGER:
    CLR C
    MOV A, R3
    SUBB A, R5
    MOV R3, A
    MOV A, R2
    SUBB A, R4
    MOV R2, A
    RET

MATH_SUB:
    JB 20H.2, SUB_FROM_NEGATIVE_ANS
    MOV A, R2
    CLR C
    SUBB A, R4
    JC SUB_RESULT_NEGATIVE
    JNZ SUB_RESULT_POSITIVE
    MOV A, R3
    CLR C
    SUBB A, R5
    JC SUB_RESULT_NEGATIVE
SUB_RESULT_POSITIVE:    CLR C
    MOV A, R3
    SUBB A, R5
    MOV R3, A
    MOV A, R2
    SUBB A, R4
    MOV R2, A
    CLR 20H.2
    RET
SUB_RESULT_NEGATIVE:
    CLR C
    MOV A, R5
    SUBB A, R3
    MOV R3, A
    MOV A, R4
    SUBB A, R2
    MOV R2, A
    SETB 20H.2
    RET
SUB_FROM_NEGATIVE_ANS:  MOV A, R3
    ADD A, R5
    MOV R3, A
    MOV A, R2
    ADDC A, R4
    MOV R2, A
    JNC SUB_NEG_OK
    LJMP ARITH_OVERFLOW
SUB_NEG_OK:             RET

MATH_MUL:
    MOV MC0, R3
    MOV MC1, R2
    MOV MC2, #00H
    MOV MC3, #00H
    MOV MUL0, R5
    MOV MUL1, R4
    MOV PROD0, #00H
    MOV PROD1, #00H
    MOV PROD2, #00H
    MOV PROD3, #00H
    MOV R0, #16
MUL16_LOOP:             MOV A, MUL0
    ANL A, #01H
    JZ MUL16_NO_ADD
    CLR C
    MOV A, PROD0
    ADD A, MC0
    MOV PROD0, A
    MOV A, PROD1
    ADDC A, MC1
    MOV PROD1, A
    MOV A, PROD2
    ADDC A, MC2
    MOV PROD2, A
    MOV A, PROD3
    ADDC A, MC3
    MOV PROD3, A
MUL16_NO_ADD:           CLR C
    MOV A, MC0
    RLC A
    MOV MC0, A
    MOV A, MC1
    RLC A
    MOV MC1, A
    MOV A, MC2
    RLC A
    MOV MC2, A
    MOV A, MC3
    RLC A
    MOV MC3, A
    CLR C
    MOV A, MUL1
    RRC A
    MOV MUL1, A
    MOV A, MUL0
    RRC A
    MOV MUL0, A
    DJNZ R0, MUL16_LOOP
    MOV A, PROD2
    ORL A, PROD3
    JZ MUL16_VALID
    LJMP ARITH_OVERFLOW
MUL16_VALID:            MOV R2, PROD1
    MOV R3, PROD0
    MOV A, R2
    ORL A, R3
    JNZ MUL16_KEEP_SIGN
    CLR 20H.2
MUL16_KEEP_SIGN:        RET

MATH_DIV:
    MOV A, R4
    ORL A, R5
    JNZ DIVISOR_VALID
    LJMP DIVIDE_BY_ZERO
DIVISOR_VALID:
    MOV TMP_H, R2
    MOV TMP_L, R3
    MOV QUO_H, #00H
    MOV QUO_L, #00H
    MOV REM_H, #00H
    MOV REM_L, #00H
    MOV R0, #16
DIV16_LOOP:
    CLR C
    MOV A, TMP_L
    RLC A
    MOV TMP_L, A
    MOV A, TMP_H
    RLC A
    MOV TMP_H, A
    MOV A, REM_L
    RLC A
    MOV REM_L, A
    MOV A, REM_H
    RLC A
    MOV REM_H, A
    MOV DIV_OVER, #00H
    JNC DIV16_NO_REM_OVER
    MOV DIV_OVER, #01H
DIV16_NO_REM_OVER:
    CLR C
    MOV A, QUO_L
    RLC A
    MOV QUO_L, A
    MOV A, QUO_H
    RLC A
    MOV QUO_H, A
    MOV A, DIV_OVER
    JNZ DIV16_SUBTRACT
    MOV A, REM_H
    CLR C
    SUBB A, R4
    JC DIV16_LESS
    JNZ DIV16_SUBTRACT
    MOV A, REM_L
    CLR C
    SUBB A, R5
    JC DIV16_LESS
DIV16_SUBTRACT:         CLR C
    MOV A, REM_L
    SUBB A, R5
    MOV REM_L, A
    MOV A, REM_H
    SUBB A, R4
    MOV REM_H, A
    ORL QUO_L, #01H
DIV16_LESS:             DJNZ R0, DIV16_LOOP
    MOV R2, QUO_H
    MOV R3, QUO_L
    MOV A, R2
    ORL A, R3
    JNZ DIV16_KEEP_SIGN
    CLR 20H.2
DIV16_KEEP_SIGN:        RET

MATH_SQUARE:
    MOV A, R2
    MOV R4, A
    MOV A, R3
    MOV R5, A
    CLR 20H.2
    LCALL MATH_MUL
    RET

LOGIC_AND:
    MOV A, R3
    ANL A, R5
    MOV R3, A
    MOV R2, #00H
    RET
LOGIC_OR:
    MOV A, R3
    ORL A, R5
    MOV R3, A
    MOV R2, #00H
    RET
LOGIC_XOR:
    MOV A, R3
    XRL A, R5
    MOV R3, A
    MOV R2, #00H
    RET
LOGIC_NOT:
    MOV A, R3
    CPL A
    MOV R3, A
    MOV R2, #00H
    RET

ARITH_OVERFLOW:         MOV ERROR_CODE, #01H
    LJMP SET_ERROR
DIVIDE_BY_ZERO:         MOV ERROR_CODE, #03H
    LJMP SET_ERROR

SET_ERROR:
    SETB 20H.0
    RET

DISPLAY_RESULT:
    LCALL LCD_CURSOR_OFF
    JB 20H.0, DISPLAY_ERROR
    MOV A, MODE
    CJNE A, #02H, DISPLAY_DECIMAL_RESULT
    LCALL LCD_PRINT_BIN8_RIGHT
    SJMP RESULT_DISPLAYED
DISPLAY_DECIMAL_RESULT: LCALL LCD_PRINT_U16_RIGHT
RESULT_DISPLAYED:
    SETB 20H.3
    RET

DISPLAY_ERROR:
    LCALL LCD_CURSOR_OFF
    LCALL LCD_CLEAR_LINE2
    MOV A, ERROR_CODE
    CJNE A, #01H, ERR_CHK_ZERO
    MOV DPTR, #STR_ERR_OVERFLOW
    SJMP ERROR_PRINT
ERR_CHK_ZERO:           CJNE A, #03H, ERR_CHK_INPUT
    MOV DPTR, #STR_ERR_DIV_ZERO
    SJMP ERROR_PRINT
ERR_CHK_INPUT:          CJNE A, #04H, ERR_CHK_OPERATOR
    MOV DPTR, #STR_ERR_INPUT
    SJMP ERROR_PRINT
ERR_CHK_OPERATOR:       CJNE A, #07H, ERR_CHK_BIT_COUNT
    MOV DPTR, #STR_ERR_BINARY
    SJMP ERROR_PRINT
ERR_CHK_BIT_COUNT:      CJNE A, #08H, ERR_UNKNOWN
    MOV DPTR, #STR_ERR_8_BITS
    SJMP ERROR_PRINT
ERR_UNKNOWN:            MOV DPTR, #STR_ERROR
ERROR_PRINT:            LCALL LCD_PUTS
    RET

LCD_PRINT_BIN8_RIGHT:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #08H
BIN8_PADDING:           MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, BIN8_PADDING
    MOV DIGIT_TMP, R3
    MOV R0, #08H
BIN8_PRINT_LOOP:        MOV A, DIGIT_TMP
    ANL A, #080H
    JZ BIN8_PRINT_ZERO
    MOV A, #'1'
    SJMP BIN8_WRITE
BIN8_PRINT_ZERO:        MOV A, #'0'
BIN8_WRITE:             LCALL LCD_DATA
    MOV A, DIGIT_TMP
    RL A
    MOV DIGIT_TMP, A
    DJNZ R0, BIN8_PRINT_LOOP
    RET

LCD_PRINT_U16_RIGHT:
    MOV TMP_H, R2
    MOV TMP_L, R3
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_CONVERT
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #0FH
U16_ZERO_PAD:           MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, U16_ZERO_PAD
    MOV A, #'0'
    LCALL LCD_DATA
    RET
U16_CONVERT:            MOV R0, #00H
U16_DIVIDE_LOOP:        LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_DIVIDE_LOOP
    MOV DIGIT_COUNT, R0
    MOV A, R0
    JNB 20H.2, U16_ALIGN_COUNT_READY
    INC A
U16_ALIGN_COUNT_READY:  MOV B, A
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, B
    MOV R1, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R1
    JZ U16_PADDING_DONE
U16_PADDING_LOOP:       MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, U16_PADDING_LOOP
U16_PADDING_DONE:
    JNB 20H.2, U16_PRINT_PREPARE
    MOV A, #'-'
    LCALL LCD_DATA
U16_PRINT_PREPARE:      MOV R0, DIGIT_COUNT
U16_PRINT_LOOP:         POP ACC
    LCALL LCD_DATA
    DJNZ R0, U16_PRINT_LOOP
    RET

DIV_TMP_BY_10:
    MOV QUO_H, #00H
    MOV QUO_L, #00H
    MOV REM_L, #00H
    MOV R1, #16
DIV10_LOOP:             CLR C
    MOV A, TMP_L
    RLC A
    MOV TMP_L, A
    MOV A, TMP_H
    RLC A
    MOV TMP_H, A
    MOV A, REM_L
    RLC A
    MOV REM_L, A
    CLR C
    MOV A, QUO_L
    RLC A
    MOV QUO_L, A
    MOV A, QUO_H
    RLC A
    MOV QUO_H, A
    MOV A, REM_L
    CLR C
    SUBB A, #10
    JC DIV10_LESS
    MOV REM_L, A
    ORL QUO_L, #01H
DIV10_LESS:             DJNZ R1, DIV10_LOOP
    MOV TMP_H, QUO_H
    MOV TMP_L, QUO_L
    MOV A, REM_L
    RET

NORMAL_SYMBOLS:     DB '+', '-', '*', '/'
LOGIC_SYMBOLS:      DB '&', '|', 'X'
STR_READY:          DB 'READY', 00H
STR_ANS:            DB 'ANS', 00H
STR_SELECT_MODES:   DB 'MODES SELECTION', 00H
STR_MODE_MENU:      DB '1:AR 2:LOG 3:ADD', 00H
STR_ARITHMETIC:     DB 'ARITHMETIC', 00H
STR_LOGICAL:        DB 'LOGIC: 0/1 ONLY', 00H
STR_ADDITIONAL:     DB 'ADDITIONAL', 00H
STR_ERR_OVERFLOW:   DB 'ERROR:OVERFLOW', 00H
STR_ERR_DIV_ZERO:   DB 'ERROR:DIV ZERO', 00H
STR_ERR_INPUT:      DB 'ERROR:INPUT SIZE', 00H
STR_ERR_BINARY:     DB 'ERROR:USE 0/1', 00H
STR_ERR_8_BITS:     DB 'ERROR:MAX 8 BIT', 00H
STR_ERROR:          DB 'ERROR', 00H
    END
